import mongoose, {Schema} from "mongoose";

const expenseSplitSchema = new Schema({
    // SplitID is auto-generated by MongoDB (_id)
    expenseID: {
        type: Schema.Types.ObjectId, // Foreign key referencing Expense collection
        ref: 'Expense',               // Reference to the Expense model
        required: true
    },
    userID: {
        type: Schema.Types.ObjectId,  // Foreign key referencing User collection
        ref: 'Users',                  // Reference to the User model
        required: true
    },
    amountOwed: {
        type: Schema.Types.Decimal128, // Decimal type for monetary values
        required: true
    }
}, {
    timestamps: true // Automatically adds createdAt and updatedAt fields
});


export const ExpenseSplit = mongoose.model("ExpenseSplit", expenseSplitSchema)