import mongoose, {Schema} from "mongoose";

const expenseStatusSchema = new Schema({
    // ExpenseStatusID is auto-generated by MongoDB (_id)
    expenseID: {
        type: Schema.Types.ObjectId, // Foreign key referencing Expense collection
        ref: 'Expense',               // Reference to the Expense model
        required: true
    },
    status: {
        type: Schema.Types.ObjectId,     // Status id of the expense (e.g., "Created", "Paid by User", "Settled")
        ref: 'Status',
        required: true
    },
    updatedBy: {
        type: Schema.Types.ObjectId,  // Foreign key referencing User collection
        ref: 'Users',                  // Reference to the User model
        required: true
    },
    updatedAt: {
        type: Date,
        default: Date.now             // Automatically set the update time to current timestamp
    }
});


export const ExpenseStatus = mongoose.model("ExpenseStatus", expenseStatusSchema)